export const testimonials = [
  {
    id: 1,
    name: "Maria Roma",
    description: "Madre de niño con TDAH",
    text: "Antes las tareas eran una batalla diaria. Ahora mi hijo termina su homework en 30 minutos. ¡Increíble!",
    image: "/placeholder.svg?height=60&width=60",
    type: "individuals",
  },
  {
    id: 2,
    name: "Juan Ramos",
    description: "Diseñador Gráfico",
    text: " Logré dejar el metilfenidato y mantener mi productividad. Jamás pensé que sería posible.Logré dejar el metilfenidato y mantener mi productividad. Jamás pensé que sería posible.",
    image: "/placeholder.svg?height=60&width=60",
    type: "individuals",
  },
  {
    id: 3,
    name: "Carlos Gonzales",
    description: "Golfista",
    text: "En competencias necesitaba máxima concentración. Mi ranking mejoró un 40% esta temporada",
    image: "/placeholder.svg?height=60&width=60",
    type: "individuals",
  },
  {
    id: 4,
    name: "Lic. Laura Mendez",
    description: "Directora Académica",
    text: "Play Attention ayudó en nuestro colegio a redujimos un 60% las derivaciones a psicopedagogía. Los profesores reportan aulas más enfocadas y menos disruptivas.",
    image: "/placeholder.svg?height=60&width=60",
    type: "companies",
  },
  {
    id: 5,
    name: "Luis Mercado",
    description: "Director de HR",
    text: "El 82% de nuestros empleados en home office sufría burnout. Con las sesiones, redujimos las bajas por estrés en un 60% en un trimestre.",
    image: "/placeholder.svg?height=60&width=60",
    type: "companies",
  },
  {
    id: 6,
    name: "Eduardo Morales",
    description: "Coach de Futbol",
    text: "Nuestro portero dejó de cometer errores por distracción en minutos cruciales. El biofeedback le enseñó a mantener la calma bajo presión, fue clave para ganar el torneo nacional.",
    image: "/placeholder.svg?height=60&width=60",
    type: "companies",
  },
  {
    id: 7,
    name: "Dra. Paula Sanchez",
    description: "Psicóloga clínica",
    text: "Gracias a Play Attention he podido medir la atención y la impulsividad de mis pacientes con TDAH de forma objetiva. He podido ajustar tratamientos con base en datos reales, y mis sesiones ahora son mucho más efectivas.",
    image: "/placeholder.svg?height=60&width=60",
    type: "professionals",
  },
  {
    id: 8,
    name: "Javier Rios",
    description: "Psicopedagogo en educación",
    text: "Gracias a esta herramienta, identificamos rápidamente dificultades de aprendizaje y diseñamos intervenciones más precisas. Los docentes reportan mejoras en el enfoque y la conducta de los alumnos.",
    image: "/placeholder.svg?height=60&width=60",
    type: "professionals",
  },
  {
    id: 9,
    name: "Dr. Andrés Beltran",
    description: "Neurólogo infantil",
    text: "La integración con EEG y pruebas cognitivas me ha permitido detectar cambios sutiles en la función cerebral. Es una herramienta esencial para el seguimiento de mis pacientes con trastornos del desarrollo.",
    image: "/placeholder.svg?height=60&width=60",
    type: "professionals",
  },
];
